model: google/gemma-4-E4B-it
api: custom
api_key_env: null
base_url: http://localhost:8000/v1
max_tokens: 64000
temperature: 0.6
concurrent_requests: 1
read_cost: 0
write_cost: 0
human_readable_id: gemma4-e4b-base
date: "2025-04-01"
other_params:
  open: true
  creator: Google
  parameters: 4
  active_parameters: 4
